
          
name: Deploy on EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          docker build -t "${{secrets.DOCKERHUB_USERNAME}}"/calculatorappmeins:latest

      - name: Docker Login
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Docker Push
        run: |
          docker push "${{secrets.DOCKERHUB_USERNAME}}"/calculatorappmeins:latest


          

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts

      - name: SSH Connection to EC2 instance
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
              sudo yum update -y
              sudo yum upgrade -y
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              docker pull "${{secrets.DOCKERHUB_USERNAME}}"/calculatorappmeins:latest

          ENDSSH

      - name: Start Docker Container on EC2 instance
        run: |
            ssh -i ~/.ssh/meinPrivateKey ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
                docker run -d -p 80:3000 --name calculatorapp2 "${{secrets.DOCKERHUB_USERNAME}}"/calculatorappmeins
            ENDSSH

      - name: Clean Up SSH Key File
        run: |
          rm meinPrivateKey

      



