
          
name: Deploy on EC2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          docker build -t "${{secrets.DOCKERHUB_USERNAME}}"/calculatorapp2meins:latest .

      - name: Docker Login
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Docker Push
        run: |
          docker push "${{secrets.DOCKERHUB_USERNAME}}"/calculatorapp2meins:latest


          

      - name: Set up SSH
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY}}" | tr -d '\r' > ~/.ssh/meinNeuerKey
          chmod 600 ~/.ssh/meinNeuerKey
          ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts
          set +x

      - name: SSH Connection to EC2 instance
        run: |
        
          ssh -i ~/.ssh/meinNeuerKey -o StrictHostKeyChecking=no ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
              sudo amazon-linux-extras enable docker
              sudo yum install -y docker
              sudo yum update -y
              sudo yum upgrade -y
              sudo systemctl start docker 
              sudo systemctl enable docker.service
              sudo usermod -aG docker ec2-user
              docker pull "${{secrets.DOCKERHUB_USERNAME}}"/calculatorapp2meins:latest

          ENDSSH

      - name: Start Docker Container on EC2 instance
        run: |
            ssh -i ~/.ssh/meinNeuerKey ec2-user@${{secrets.EC2_IP}} << 'ENDSSH'
                docker stop calculatorapp2meins || true
                docker rm calculatorapp2meins || true
                docker run -d -p 80:3001 --name calculatorapp2meins "${{secrets.DOCKERHUB_USERNAME}}"/calculatorapp2meins
            ENDSSH

      - name: Clean Up SSH Key File
        run: |
          rm ~/.ssh/meinNeuerKey




      




